/* Fall Line 简体中文显示层：仅翻译文字，保留玩法、存档和 CSS 状态标识。 */
(() => {
  const phrases = {
    'FALL LINE — Freeride Mountain': '雪山速降 — 自由滑雪',
    'FALL LINE · MONT VIREAUX': '雪山速降 · 维罗雪山',
    'MONT VIREAUX · FALL LINE': '维罗雪山 · 雪山速降',
    'MONT VIREAUX PRO 156': '维罗专业雪板 156',
    'FALL LINE': '雪山速降', 'FALL': '雪山', 'LINE': '速降',
    'Mont Vireaux': '维罗雪山', 'Vireaux Summit': '维罗山顶',
    "Crow's Couloir Line": '乌鸦峡谷挑战', "Crow's Couloir": '乌鸦峡谷',
    'Raven Chute': '渡鸦陡槽', 'The Steps': '阶梯断崖',
    'Sunbowl Cornice': '向阳雪碗雪檐', 'Sunbowl Freeride': '向阳雪碗自由滑行',
    'Sunbowl': '向阳雪碗', 'Pillow Garden': '雪枕花园', 'Pillow Pop': '雪枕跳跃挑战',
    'Whalebacks': '鲸背雪坡', 'Larch Glades': '落叶松林间雪道',
    'East Woods': '东侧森林', 'Vireaux Piste': '维罗压雪道',
    'Aurel Park Jam': '奥雷尔公园技巧赛', 'Aurel Park': '奥雷尔地形公园',
    'Aurel Superpipe': '奥雷尔超级 U 型池', 'Vireaux Village': '维罗山村',
    'Vireaux Downhill': '维罗速降赛', 'Glade Rush': '林间竞速赛',
    'Superpipe Session': '超级 U 型池技巧赛', 'Summit to Valley': '山顶至山谷挑战',
    'VIREAUX HUT': '维罗山屋', 'VIREAUX EXPRESS': '维罗快线缆车',
    'MID STATION · 2,190 m': '中转站 · 2,190 米', 'RUN 2 · SPLIT 3': '第 2 趟 · 第 3 分段',
    'The top of the massif. Steep open faces fall away on every side.': '山脉最高处，四周都是陡峭开阔的山坡。',
    'A narrow rock-walled chute. Commit and hold your edge.': '两侧岩壁夹着狭窄陡槽。果断下滑，稳住板刃。',
    'Cliff bands stacked like stairs. Pick your drop.': '层层断崖像阶梯一样排列。选好你的落点。',
    'Drop the cornice into a wide powder bowl with wind lips.': '跃下雪檐，进入宽阔的粉雪碗，借风积雪坡起跳。',
    'Stacked powder pillows. Pop, float, repeat.': '层叠的粉雪雪枕，起跳、腾空，再来一次。',
    'Tree runs through deep powder and fallen logs.': '在深粉雪与倒木之间，穿梭林间雪道。',
    'Groomed corduroy from mid-mountain to the village.': '从半山腰一路延伸到山村的压雪道。',
    'Kickers, rails and boxes. The judges are watching.': '跳台、栏杆和滑箱齐备，裁判正在观察你的表现。',
    'A 150 m superpipe with 6 m walls. Go up, spin, come back down.': '长 150 米、池壁高 6 米的超级 U 型池。冲上池壁，旋转，再稳稳落回。',
    'Score as many points as you can in the park in 90 seconds. Variety, amplitude and clean landings pay.': '在 90 秒内尽量得分。动作多样、腾空高度和稳定落地都会加分。',
    'Race the groomed piste to the village. Miss a gate: +5 s.': '沿压雪道竞速滑向山村。每漏过一道旗门，罚时 5 秒。',
    'Ride the couloir and the face below. The judges score every trick, drop and clean mile.': '滑过峡谷及下方山坡。技巧动作、落差跳跃和稳定滑行都会计分。',
    'Drop the cornice, hit the wind lips, keep it flowing to the bottom of the bowl.': '跃下雪檐，借风积雪坡起跳，一路流畅滑到雪碗底部。',
    'Pop off every pillow you can. 45 seconds.': '在 45 秒内，尽量从更多雪枕上起跳。',
    'Thread the glades to the park. Trees do not move.': '穿过林间雪道抵达公园。小心避开树木。',
    'One run down the superpipe. Amplitude, rotation and clean landings on the walls.': '完成一趟超级 U 型池滑行。靠腾空高度、旋转和池壁上的稳定落地得分。',
    'The whole mountain in one run. Style, speed and air all count.': '一趟滑遍整座山。技巧、速度和腾空表现都会计分。',
    'Your own line. Drop in exactly where you clicked on the mountain.': '选择自己的路线。从你点击的山上位置直接出发。',
    'Select a drop zone or event · or click anywhere on the mountain': '选择出发点或赛事，也可以点击山上的任意位置',
    'LARCH GLADES TO THE RAIL LINE': '落叶松林间雪道 → 栏杆路线',
    'SUNBOWL TO AUREL PARK': '向阳雪碗 → 奥雷尔地形公园',
    'Demo run · press any key to ride': '自动演示 · 按任意键开始滑行',
    'PRESS ANY KEY TO RIDE': '按任意键开始滑行',
    'FREE RIDE — PRESS M FOR THE MOUNTAIN MAP': '自由滑行 — 按 M 打开雪山地图',
    'TIME OF DAY: GOLDEN HOUR': '时段：粉紫晚霞', 'TIME OF DAY: MORNING': '时段：清晨',
    'WEATHER: SNOWFALL': '天气：降雪', 'WEATHER: CLEAR MORNING': '天气：晴朗',
    'CRASHED — COMBO LOST': '摔倒了 — 连招分数丢失',
    'STUCK? HOLD W TO SKATE · R TO RESPAWN': '卡住了？按住 W 向前滑动 · 按 R 重新出发',
    'D-PAD ↓ — INSTANT REPLAY': '方向键 ↓ — 即时回放',
    'PRESS V — INSTANT REPLAY': '按 V — 即时回放', ' — PRESS E TO START': ' — 按 E 开始',
    'PRESS E TO START': '按 E 开始赛事',
    'TIP: HOLD A TO CHARGE, RELEASE RIGHT AT THE LIP FOR A PERFECT POP': '提示：按住手柄 A 蓄力，在跳台边缘松开，完成完美起跳',
    'TIP: HOLD THE LEFT STICK WHILE CHARGING TO PRE-WIND A SPIN': '提示：蓄力时推动左摇杆，提前准备旋转',
    'TIP: RIGHT STICK GRABS — HOLD IT LONGER (AND CLICK) TO TWEAK': '提示：右摇杆抓板 — 持续推动并按下摇杆，可加大动作幅度',
    'TIP: LET GO OF THE STICK AND THE RIDER SPOTS THE LANDING': '提示：松开摇杆，滑手会自动调整姿态准备落地',
    'TIP: LAND IN THE STEEP PART OF A SLOPE — FLAT LANDINGS HURT': '提示：尽量落在较陡的坡面上，平地落地的冲击更大',
    'TIP: CHAIN TRICKS WITHIN 2.5 S — EVERY NEW TRICK RAISES THE MULTIPLIER': '提示：在 2.5 秒内衔接动作，每个新动作都会提高连招倍率',
    'TIP: HOLD SPACE TO CHARGE, RELEASE RIGHT AT THE LIP FOR A PERFECT POP': '提示：按住空格蓄力，在跳台边缘松开，完成完美起跳',
    'TIP: HOLD A OR D WHILE CHARGING TO PRE-WIND A SPIN': '提示：蓄力时按住 A 或 D，提前准备旋转',
    'TIP: ARROW KEYS GRAB — HOLD LONGER (SHIFT FOR ALT GRABS) TO TWEAK': '提示：方向键抓板 — 按住可加大幅度，配合 Shift 使用另一组抓板动作',
    'TIP: RELEASE THE SPIN KEY AND THE RIDER SPOTS THE LANDING': '提示：松开旋转键，滑手会自动调整姿态准备落地',
    'TIP: W TUCKS FOR SPEED, S DIGS IN A HOCKEY STOP, ↑ + A/D BUTTERS': '提示：W 收身加速，S 急停刹车，↑ 配合 A/D 做压板旋转',
    'TIP: PRESS V FOR AN INSTANT REPLAY OF YOUR LAST AIR': '提示：按 V 即时回放上一次腾空动作',
    'Generating mountain': '正在生成雪山', 'Shaping the park': '正在建造地形公园',
    'Lighting the snow': '正在设置雪地光照', 'Growing forests': '正在生成森林',
    'Waking the rider': '正在准备滑手', 'Error:': '加载失败：',
    'Drop-in Map': '雪山出发地图', 'Mountain map': '雪山地图',
    'Drop Zones': '出发点', 'Drop zone': '出发点', 'Custom drop': '自选出发点',
    'Start event here': '在此开始赛事', 'Start event at a beacon': '在赛事标记处开始',
    'Start event': '开始赛事', 'Drop in': '从这里出发',
    'Switch Discipline': '切换单板 / 双板', 'To Snowboard': '切换至单板', 'To Ski': '切换至双板',
    'Snowboard': '单板', 'SKIS': '双板', 'Ski': '双板', 'Discipline': '滑雪类型',
    'Follow Cam': '跟随视角', 'Helmet Cam': '第一人称视角', 'Cinematic': '电影视角',
    'Trick Event': '技巧赛', 'Freeride Event': '自由滑行赛', 'Freeride': '自由滑行',
    'Restart Run': '重新开始', 'Run Complete': '滑行完成', 'Run Score': '本趟得分',
    'Audio Volume': '音量', 'Personal best': '个人最佳', 'NEW PERSONAL BEST': '刷新个人最佳',
    'Top of the podium': '登上最高领奖台', 'No Medal': '未获奖牌',
    'Tricks landed': '成功完成的动作', 'Breakdown': '成绩明细',
    'Clock time': '实际用时', 'Missed gates': '漏过旗门', 'Clean sheet': '全部通过',
    'Top speed': '最高速度', 'Crashes': '摔倒次数', 'No falls': '没有摔倒',
    'Each crash costs the respawn time': '每次摔倒都会损失重新出发的时间',
    'Style points (not timed)': '技巧得分（不影响计时）',
    'Best combo': '最佳连招', 'Landings': '落地表现',
    'Perfect / Clean / Sketchy': '完美 / 稳定 / 勉强', 'Air time': '腾空时间',
    'Big drops': '大落差跳跃', 'Line completed': '路线完成度',
    'No crashes': '没有摔倒', 'Unbanked combos lost': '未结算的连招分数丢失', 'Flawless': '零失误',
    'Riding (pad: left stick / A / B)': '地面滑行（手柄：左摇杆 / A / B）',
    'Air (pad: left stick / right stick)': '空中动作（手柄：左摇杆 / 右摇杆）',
    'Rails & boxes': '栏杆与滑箱', 'Game': '游戏操作',
    'Steer · edge': '转向 · 立刃', 'Steer · set the edge': '转向 · 控制板刃',
    'Steer · ↑ tuck · ↓ brake': '转向 · ↑ 收身 · ↓ 刹车',
    'Tuck · skate on flats': '收身加速 · 平地滑行', 'Brake · lean back': '刹车 · 重心后移',
    'Brake · lean back in powder': '刹车 · 粉雪中重心后移',
    'Hold: charge · release: pop': '按住蓄力 · 松开起跳',
    'Nose / tail press': '板头 / 板尾压板', 'Press · butter with A/D': '压板 · 配合 A/D 压板旋转',
    'Ski / board': '切换单板 / 双板', 'Ski ⇄ snowboard': '双板 ⇄ 单板',
    'Front / back flip': '前空翻 / 后空翻', 'Grab (8 directions)': '抓板（8 个方向）',
    'Alt grabs': '另一组抓板动作', 'Tweak it out': '加大动作幅度', 'Off-axis corks': '离轴转体',
    'Spin · flip': '旋转 · 空翻', 'Quick grabs': '快捷抓板', 'Pop off': '跳离栏杆',
    'Spin · release to land it': '旋转 · 松开准备落地',
    'Corks · rodeos · mistys': '离轴转体 · 罗迪欧翻转 · 米斯蒂翻转',
    'Grab · hold to tweak': '抓板 · 按住加大幅度', '+ arrows: alt grabs': '+ 方向键：另一组抓板',
    'Map · click to drop anywhere': '地图 · 点击任意位置出发',
    'Respawn / restart': '重新出发 / 重开', 'Stance · outfit · weather': '站姿 · 服装 · 天气',
    'Morning ⇄ golden hour': '清晨 ⇄ 粉紫晚霞', 'Instant replay': '即时回放',
    '50-50 ↔ boardslide': '顺板滑杆 ↔ 横板滑杆', '50-50 ↔ slide': '顺板滑杆 ↔ 横板滑杆',
    'Drops / Events': '出发点 / 赛事',
    'MORE IN COMBO': '个连招动作', 'MEDAL TIME': '奖牌目标时间', 'MAX AIR': '最长腾空',
    'PERFECT POP': '完美起跳', 'OUT OF BOUNDS': '超出边界', 'Combo lost': '连招丢失',
    'Caught an edge': '卡刃摔倒', 'Over-rotated': '旋转过度', 'Landed sideways': '横向落地',
    'Too much impact': '落地冲击过大', 'Hit a tree': '撞到树木',
    'Hit a building': '撞到建筑', 'Hit a rock': '撞到岩石', 'Wipeout': '摔倒',
    'Wind Crust': '风硬雪壳', 'Powder': '粉雪', 'Groomed': '压雪', 'Slush': '湿雪', 'Rock': '岩石', 'Ice': '冰面',
    'Regular': '左脚在前', 'Goofy': '右脚在前', 'Switch': '反脚',
    'Rail 50-50': '顺板滑杆', 'Rail Slide': '横板滑杆', 'Boardslide': '横板滑杆',
    'Nosepress': '板头压杆', 'Tailpress': '板尾压杆', '50-50': '顺板滑杆',
    'Nose Butter': '板头压板旋转', 'Tail Butter': '板尾压板旋转', 'Butter': '压板旋转',
    'Cliff Drop': '断崖跳落', 'Straight Air': '直体腾空', 'Clean Riding x': '稳定滑行 ×',
    'Powder Turn': '粉雪转弯', 'Deep Carve': '深度刻滑', 'Tree Skim': '贴树滑过',
    'Nose Grab': '抓板头', 'Tail Grab': '抓板尾', 'Tweaked Mute': '大幅度穆特抓板',
    'Tweaked Japan': '大幅度日式抓板', 'Tweaked Stalefish': '大幅度后手后刃抓板',
    'Power Method': '强力屈膝抓板', 'Roast Beef': '穿腿抓后刃',
    'Truck Driver': '双手抓板', 'Seatbelt': '安全带式抓板', 'Double Japan': '双重日式抓板',
    'Tweaked Tail': '大幅度抓板尾', 'Indy': '后手前刃抓板', 'Mute': '穆特抓板',
    'Melon': '前手后刃抓板', 'Stalefish': '后手后刃抓板', 'Method': '屈膝展板抓板',
    'Japan': '日式抓板', 'Crail': '后手抓板头', 'Safety': '外侧抓板',
    'Critical': '交叉抓板', 'Blunt': '钝式抓板', 'Octograb': '双手交叉抓板',
    'Frontside': '正面旋转', 'Backside': '背面旋转', 'Frontflip': '前空翻', 'Backflip': '后空翻',
    'Misty': '米斯蒂翻转', 'Rodeo': '罗迪欧翻转', 'Cork': '离轴转体', 'Cab': '反脚正面旋转',
    'Double': '双重', 'Triple': '三重', 'Quad': '四重', 'Tweaked': '加大幅度',
    'Nose': '板头', 'Tail': '板尾', 'Grab': '抓板', 'Drop': '落差跳跃', 'Log': '原木',
    'Small Kicker': '小型跳台', 'Medium Kicker': '中型跳台', 'Large Kicker': '大型跳台',
    'XL Kicker': '超大跳台', 'Kicker': '跳台', 'On-ramp': '上栏坡道',
    'Flat Box': '平滑箱', 'Flat Rail': '水平栏杆', 'Down Rail': '下坡栏杆', 'Long Box': '长滑箱',
    'Kinked Rail': '折角栏杆', 'Rainbow Box': '弧形滑箱', 'Big Tube': '大型圆管',
    'Big Air': '大跳台', 'Superpipe': '超级 U 型池', 'Glade': '林间雪道',
    'HOLD GRAB': '持续抓板', 'ARROWS': '方向键', 'RS CLICK': '按下右摇杆',
    'D-PAD': '方向键', 'LS': '左摇杆', 'RS': '右摇杆',
    'SPACE': '空格', 'ENTER': '回车', 'MOUSE': '鼠标', 'LMB': '左键', 'RMB': '右键',
    'Resume': '继续滑行', 'Retry': '再试一次', 'Continue': '继续', 'Controls': '操作说明',
    'Confirm': '确认', 'Select': '选择', 'Navigate': '切换选项', 'Close': '关闭', 'Back': '返回',
    'Events': '赛事', 'Event': '赛事', 'Race': '竞速赛', 'Tricks': '技巧动作', 'Trick': '技巧',
    'Camera': '视角', 'Map': '地图', 'Pause': '暂停', 'Respawn': '重新出发', 'Replay': '回放',
    'Weather': '天气', 'Time of day': '时段', 'Outfit': '服装', 'Stance': '站姿',
    'Tuck': '收身加速', 'Brake': '刹车', 'Spin': '旋转', 'Press': '压板', 'Tweak': '加大幅度',
    'Riding': '滑行得分', 'Altitude': '海拔', 'Distance': '距离', 'Results': '成绩结算', 'Run': '本趟滑行',
    'Medal': '奖牌', 'Gold': '金牌', 'Silver': '银牌', 'Bronze': '铜牌',
    'PAUSED': '已暂停', 'FINISH': '终点', 'START': '起点', 'DEMO': '自动演示',
    'BANKED': '已结算', 'PERFECT': '完美落地', 'CLEAN': '稳定落地', 'SKETCHY': '勉强落地',
    'CRASH': '摔倒', 'BAIL': '摔倒', 'REPLAY': '回放', 'CHECKPOINT': '检查点',
    'MISSED GATE': '漏过旗门', 'NEW AREA': '到达新区域', 'BIG AIR': '大腾空',
    'SCORE': '得分', 'ALT': '海拔', 'AIR': '腾空', 'CP': '检查点', 'PTS': '分',
    'KM/H': '公里/时', 'km/h': '公里/时', 'KM': '公里', 'FPS': '帧/秒', 'PACE': '目标', 'MISSED': '未达成',
    'SUMMIT': '山顶', 'NONE': '无', 'NEXT': '下一目标', 'YOU': '你的位置',
    'GO!': '出发！', 'GO': '出发', 'Left': '向左', 'Right': '向右', 'AT': '目标',
    'gates': '道旗门', 'tricks': '个技巧动作', 'landed': '个成功动作', 'grinds': '次滑杆',
    'multiplier': '倍率', 'longest': '最长', 'speed': '速度', 'carves': '刻滑',
    'powder': '粉雪', 'trees': '贴树滑行', 'streaks': '连续稳定滑行', 'drops': '次落差跳跃',
    'penalty': '罚时', 'crash(es) reduce it': '次摔倒，完成奖励减少',
    'follow': '跟随视角', 'helmet': '第一人称视角', 'cinematic': '电影视角',
  };
  const entries = new Map();
  for (const [en, zh] of Object.entries(phrases)) {
    entries.set(en, zh);
    entries.set(en.toUpperCase(), zh);
    entries.set(en.replaceAll('&', '&amp;'), zh);
    entries.set(en.toUpperCase().replaceAll('&', '&amp;'), zh);
  }
  // Lowercase medal names appear as text as well as CSS keys; html() never translates tags.
  for (const [en, zh] of [['gold', '金牌'], ['silver', '银牌'], ['bronze', '铜牌']]) entries.set(en, zh);
  const escape = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const pattern = new RegExp('(?<![A-Za-z])(?:' + [...entries.keys()].sort((a,b) => b.length-a.length).map(escape).join('|') + ')(?![A-Za-z])', 'g');
  const cache = new Map();
  function text(value) {
    const s = String(value ?? '');
    if (!/[A-Za-z]/.test(s)) return s;
    if (cache.has(s)) return cache.get(s);
    let out = s.replace(pattern, match => entries.get(match));
    out = out.replace(/(?<=\d)\s+[mM]\b/g, ' 米').replace(/(?<=\d)\s+[sS]\b/g, ' 秒').replace(/\bpts\b/g, '分').replace(/\bx(?=\d)/g, '×');
    if (cache.size > 1000) cache.clear();
    cache.set(s, out);
    return out;
  }
  function html(value) {
    return String(value ?? '').split(/(<[^>]*>)/g).map(part => part.startsWith('<')
      ? part.replace(/(aria-label|title|placeholder)="([^"]*)"/g, (_, attr, val) => `${attr}="${text(val)}"`)
      : text(part)).join('');
  }
  window.FL_ZH = Object.freeze({ text, html });
})();
